# Generated by Django 5.0.1 on 2024-02-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_song', models.CharField(max_length=128)),
                ('path_to_img', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=64)),
            ],
        ),
    ]
